apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'crud-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['crud-service:80']

      # keep any future scrape jobs here
